config/routes.rb
Rails.application.routes.draw do
  get 'questions/index'

  get 'recharge_homes/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/auth', to: 'authentication#autenthicate_user'
  get '/logout', to: 'authentication#logout_user'
  get '/audited/:model/:id', to: 'audited#index'


  resources :inboxes
  resources :subscribers

  namespace :api do
    namespace :v1 do
      post '/logout', to: 'users#logout'
      get '/me', to: 'users#me'
      get '/password_update/:id', to:'users#show'
      put '/password_update/:id', to:'users#password_update'
      resources :users
      resources :drivers
      resources :packages
      resources :recharges
      resources :questions
      resources :recharge_homes
      resources :taxis
      resources :assign_taxis
      resources :services
      resources :charts
    end
  end

  resources :taxis 
  resources :drivers 
  resources :packages
  resources :recharge_homes
  resources :questions

  get 'logout_driver/:taxi_id/:user_id', to: 'taxis#logout_driver', as: :logout_driver_and_taxi
  get 'add_driver_to_taxi/:taxi_id/:user_id', to: 'taxis#add_driver', as: :add_driver_to_taxi
  get 'remove_driver_from_taxi/:taxi_id/:user_id', to: 'taxis#remove_driver', as: :remove_driver_to_taxi


  get 'users/sign_in', to: 'users#sign_in', as: :sign_in
  get 'users/logout_user', to: 'users#logout_user', as: :logout_user
  post 'users/sign_in', to: 'users#new_session', as: :new_session

  root :controller => 'home', :action => 'home'
  mount Shrine.presign_endpoint(:cache) => '/presign'
end

app/models/taxi.rb
class Taxi < ApplicationRecord
  has_and_belongs_to_many :users
  before_validation :rules
  scope :modelo_filter, ->(modelo) { where('modelo like ?', "#{modelo}%") }



  def es_ocupado_por? driver
    ocupado_por == driver.id
  end

  def logout driver_id
    update_attributes(ocupado: false) &&  update_attributes(ocupado_por: nil) && User.find(driver_id).update_attributes(token: nil)
  end

  
  private
  def self.ransackable_scopes(auth_object = nil)
    %i(modelo_filter)
  end

  def rules
    errors.add(:placa, 'La placa ya existe.') if placa_exists?
  end

  def placa_exists? 
    taxi = Taxi.find_by(placa: self.placa) 
    return true if taxi.present? && taxi.id != self.id
  end



end

app/controllers/api/v1/taxis_controller.rb
module Api::V1
class TaxisController < BaseController

	before_action :set_taxi, only:[:update, :destroy, :show]

	def index
		unless filter
			@taxis = Taxi.all
			json_response(@taxis, @taxis.count)
		end
	end

	def create
		@taxi = Taxi.create(taxi_params)
		json_response(@taxi, 0, :created)
	end 

	def show 
		json_response(@taxi)
	end 

	def update
		@taxi.update(taxi_params)
		json_response(@taxi, :updated)
	end 

	def destroy
		@taxi.destroy
		json_response(@taxi, :deleted)
	end

	private 

		def taxi_params
			params.permit(
				:placa,
				:ciudad,
				:marca,
				:modelo,
				:baul,
				:nombre_propietario,
				:telefono_propietario,
				:proxima_revision,
				:activo,
				:ocupado
			)
		end 

		def set_taxi
			@taxi = Taxi.find(params[:id])
		end

		def filter
	      return unless params[:search]
	      @taxis = TaxisHelper.get_taxi_by_search params[:search]
	      json_response(@taxis, @taxis.count)
	    end

	end
end 

app/controllers/taxis_controller.rb
class TaxisController < LockController
  before_action :taxis, only: [:index]
  before_action :set_taxi, only: [:edit, :update, :add_driver, :remove_driver]
  before_action :set_taxista, only: [:add_driver, :remove_driver]
  
  breadcrumb 'Taxis', :taxis_path
  breadcrumb 'Crear', :new_taxi_path, only: [:new]

  def index
  end

  def new
    @taxi = Taxi.new
  end

  def edit
    @drivers = User.with_role(:driver).where.not(id: @taxi.users.pluck(:id)).ransack(params[:q]).result 
  end

  def create
    @taxi = Taxi.new(taxi_params)
    if @taxi.save
      flash[:success] = 'El taxi fue registrado correctamente!'
      redirect_to edit_taxi_path(@taxi)
    else
      flash[:error] = 'Error al registrar el taxi!'
      render :new
    end
  end


  def update
    if @taxi.update_attributes(taxi_params)
      flash[:success] = 'El taxi fue modificado correctamente!'
      redirect_to edit_taxi_path(@taxi)
    else
      flash[:error] = 'Error al modificar el taxi!'
      render :new
    end
  end

  def logout_driver
    @taxi = Taxi.find(params[:taxi_id])
    if @taxi.logout(params[:user_id])
      redirect_back fallback_location: taxis_url, notice: 'El taxi ahora esta libre'
    else
      redirect_back fallback_location: taxis_url, notice: 'Problemas al cerrar sesión del taxi.'
    end
  end


  def add_driver
    if @taxista.assign_taxi(@taxi)
      redirect_back fallback_location: taxis_url, notice: "El taxista #{@taxista.nombre} fue agreado al taxi con placas #{@taxi.placa}."
    else
      redirect_back fallback_location: taxis_url, notice: 'Error al asignar taxista.'
    end
  end

  def remove_driver
    if @taxista.taxis.destroy(@taxi)
      redirect_back fallback_location: taxis_url, notice: "El taxista #{@taxista.nombre} fue removido del taxi con placas #{@taxi.placa}."
    else
      redirect_back fallback_location: taxis_url, notice: 'Error al remover taxista.'
    end
  end

  private

  def taxi_params
    params.require(:taxi).permit(
      :placa,
      :modelo,
      :marca,
      :baul,
      :ciudad,
      :proxima_revision,
      :telefono_propietario,
      :nombre_propietario,
      :activo
    )
  end

  def set_taxi
    id = params[:id] || params[:taxi_id]
    @taxi = Taxi.find(id)
  end

  def taxis
    @q = Taxi.ransack(params[:q])
    @taxis = @q.result(distinct: true)
  end

  def set_taxista
    @taxista = User.find(params[:user_id])
  end
end

app/helpers/taxis_helper.rb
module TaxisHelper

  def self.get_taxi_by_search q
    Taxi.where("lower(placa) LIKE '%#{q.downcase}%' OR lower(marca) LIKE '%#{q.downcase}%' OR lower(nombre_propietario) LIKE '%#{q.downcase}%' OR lower(ciudad) LIKE '%#{q.downcase}%'")
  end

end

app/views/taxis/_drivers_all.html.haml
.int-content
  .form-title Todos los conductores
  %table.table
    %tbody
      - @drivers.each do |driver|
        %tr
          %td{scope: 'row'}
            = driver.nombre
          %td{scope: 'row'}
            - unless @taxi.users.exists?(driver.id)
              = link_to 'Agregar al taxi', add_driver_to_taxi_path({taxi_id: @taxi.id, user_id: driver.id})

app/views/taxis/_drivers_in.html.haml
.int-content
  .form-title Conductores asociados a este taxi
  %table.table
    %tbody
      - users = @taxi.users
      - if users.count > 0 
        - users.each do |driver|
          %tr
            %td{scope: 'row'}
              = driver.nombre
            %td{scope: 'row'}
              = link_to 'Remover del taxi', remove_driver_to_taxi_path({taxi_id: @taxi.id, user_id: driver.id})
            %td{scope: 'row'}
              - if @taxi.es_ocupado_por? driver
                = link_to 'Cerrar sesión', logout_driver_and_taxi_path({taxi_id: @taxi.id, user_id: driver.id}), class: 'link-red'

      - else
        .warning-message
          Este taxi no tiene taxistas

app/views/taxis/_filter.html.haml
.row
  .gray-frame
    = search_form_for @q, class: 'filters' do |f|
      .row
        .col-md-2.col-sm-12.col
          = f.label :modelo
          = f.search_field :modelo_eq, class: 'form-control'
        .col-md-2.col-sm-12.col
          = f.label :placa
          = f.search_field :placa_cont, class: 'form-control'
        .col-md-2.col-sm-12.col-sm-12.col
          = f.label :marca
          = f.search_field :marca_cont, class: 'form-control'
        .col-md-2.col-sm-12.col-sm-12.col
          = f.label 'Ocupado?'
          = f.select :ocupado_false,  options_for_select([['No', 1], ['Si', 0]]), { include_hidden: false }, class: 'form-control'
        .col-md-1.col-sm-12.col.actions
          = f.submit 'Buscar', class: 'btn btn-primary'
      

app/views/taxis/_form.html.haml
= bootstrap_form_for(@taxi) do |f|
  .row
    .col-md-3
      = f.text_field :placa, {required: 'required'}
    .col-md-3
      = f.text_field :marca, {required: 'required'}
    .col-md-3
      = f.number_field :modelo, min: 1995, max: 2099, value: Time.current.year
    .col-md-3
      = f.text_field :ciudad, {required: 'required'}
  .row    
    .col-md-3
      = f.date_field :proxima_revision, {required: 'required'}
    .col-md-6
      = f.text_field :nombre_propietario, {required: 'required'}
    .col-md-3
      = f.text_field :telefono_propietario, {required: 'required'}
  .row
    .col-md-3
      = f.check_box :baul, label: 'El taxi tiene baúl'
    .col-md-3
      = f.check_box :activo, label: 'Activar taxi'
  .row
    .actions-form
      - if @taxi.new_record?
        = f.submit 'Crear', class: 'btn btn-primary'
      - else
        = f.submit 'Actualizar', class: 'btn btn-primary'

app/views/taxis/edit.html.haml
.int-content
	.form-title Editando taxi con placa #{@taxi.placa}
	= render partial: 'form'
.row
	.col-md-6
		= render partial: 'drivers_all'
	.col-md-6
		= render partial: 'drivers_in'
	

app/views/taxis/index.html.haml
.int-content
  .form-title
    Lista de taxis
    .model-action
      %span.badge.badge-secondary.secondary
        = link_to 'Crear Taxi', new_taxi_path
  = render partial: 'filter'
  .horizontal-divider
  .row 
    - @taxis.each do |taxi|
      .col-sm-4.col-xs-12.col-md-3.col-lg-2
        .thumbnail
          .gray-rectangle
            %span
              = taxi.placa
          .caption
            .taxi
              .marca
                %span
                  = taxi.modelo
                %span
                  = taxi.marca
              .actions
                = link_to 'Ver', edit_taxi_path(taxi.id)
   

app/views/taxis/new.html.haml
.int-content
	.form-title Nuevo taxi
	= render partial: 'form'