config/routes.rb
Rails.application.routes.draw do
  get 'questions/index'

  get 'recharge_homes/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/auth', to: 'authentication#autenthicate_user'
  get '/logout', to: 'authentication#logout_user'
  get '/audited/:model/:id', to: 'audited#index'


  resources :inboxes
  resources :subscribers

  namespace :api do
    namespace :v1 do
      post '/logout', to: 'users#logout'
      get '/me', to: 'users#me'
      get '/password_update/:id', to:'users#show'
      put '/password_update/:id', to:'users#password_update'
      resources :users
      resources :drivers
      resources :packages
      resources :recharges
      resources :questions
      resources :recharge_homes
      resources :taxis
      resources :assign_taxis
      resources :services
      resources :charts
    end
  end

  resources :taxis 
  resources :drivers 
  resources :packages
  resources :recharge_homes
  resources :questions

  get 'logout_driver/:taxi_id/:user_id', to: 'taxis#logout_driver', as: :logout_driver_and_taxi
  get 'add_driver_to_taxi/:taxi_id/:user_id', to: 'taxis#add_driver', as: :add_driver_to_taxi
  get 'remove_driver_from_taxi/:taxi_id/:user_id', to: 'taxis#remove_driver', as: :remove_driver_to_taxi


  get 'users/sign_in', to: 'users#sign_in', as: :sign_in
  get 'users/logout_user', to: 'users#logout_user', as: :logout_user
  post 'users/sign_in', to: 'users#new_session', as: :new_session

  root :controller => 'home', :action => 'home'
  mount Shrine.presign_endpoint(:cache) => '/presign'
end

app/controllers/api/v1/drivers_controller.rb
module Api::V1
  class DriversController < BaseController
    before_action :set_driver, only: [:show, :update, :destroy]
    before_action :get_foto, only: [:create, :update]

    def index
      unless filter
        @drivers = User.order(nombre: :asc).with_role :driver
        json_response(@drivers, @drivers.count)
      end
    end

    def show
      json_response(@driver)
    end

    def update
      @driver.update(driver_params)
      json_response(@driver)
    end

    def create
      @driver = User.create!(driver_params)
      @driver.be_driver
      json_response(@driver, 0 , :created)
    end

    private

    def driver_params
      params.permit(
        :nombre, 
        :cedula,
        :email,
        :foto,
        :telefono, 
        :activo, 
        :direccion
      )

    end

    def set_driver
      @driver = User.find(params[:id])
    end

    def get_foto
      return if params[:foto].nil?
      params[:foto] = params[:foto]["content"]
    end

    def filter
      return unless params[:search]
      @drivers = DriversHelper.get_driver_by_search params[:search]
      json_response(@drivers, @drivers.count)
    end

  end
end

app/controllers/drivers_controller.rb
class DriversController < LockController
  before_action :set_driver, only: [:show, :update, :destroy, :edit]
  before_action :drivers, only: [:index]
  #before_action :get_foto, only: [:create, :update]

  def new
    @driver = User.new
  end

  def index
  end

  def edit

  end

  def show
  end

  def update
    if @driver.update(driver_params_edit)
      flash[:success] = 'El taxista fue actualizado correctamente!'
      redirect_to edit_driver_path(@driver)
    else
      flash[:error] = 'Error al actualizar el taxista!'
      render :edit
    end
  end

  def create
    @driver = User.new(driver_params)
    if @driver.save
      @driver.be_driver
      flash[:success] = 'El taxista fue registrado correctamente!'
      redirect_to edit_driver_path(@driver)
    else
      flash[:error] = 'Error al registrar el taxista!'
      render :new
    end
  end

  private

  def driver_params
    params.permit(
      :nombre, 
      :cedula,
      :email,
      :foto,
      :telefono, 
      :activo, 
      :direccion,
      :docs,
      :photo
    )

  end

  def driver_params_edit
    params.require(:user).permit(
      :nombre, 
      :cedula,
      :email,
      :foto,
      :telefono, 
      :activo, 
      :direccion,
      :docs,
      :photo
    )

  end

  def set_driver
    @driver = User.find(params[:id])
  end

  def get_foto
    return if params[:foto].nil?
    params[:foto] = params[:foto]["content"]
  end

  def drivers
    @q = User.with_role(:driver).ransack(params[:q])
    @drivers = @q.result(distinct: true)
  end

end

app/helpers/drivers_helper.rb
module DriversHelper

  def self.get_driver_by_search q
    User.where("lower(nombre) LIKE '%#{q.downcase}%' OR telefono LIKE '%#{q}%' OR email LIKE '%#{q}%'").with_role :driver
  end

end

app/views/drivers/_edit_form.html.haml
= bootstrap_form_for(@driver, url: driver_path) do |f|
  .row
    .col-md-3
      = f.text_field :nombre, {required: 'required'}
    .col-md-3
      = f.text_field :cedula, {required: 'required'}
    .col-md-3
      = f.email_field :email
    .col-md-3
      = f.phone_field :telefono
  .row    
    .col-md-6
      = f.text_area :direccion
    .col-md-3
      = f.form_group :activo, label: { text: '¿Activar el taxista?' } do
        = f.check_box :activo, label: 'Activar'
  .row
    .col-md-3
      = f.file_field :photo, as: :file, accept: DriverPhotoUploader::ALLOWED_TYPES.join(',')
    .col-md-3
      = f.file_field :docs, as: :file, accept: DocsUploader::ALLOWED_TYPES.join(',')
  .row
    .col-md-3
      - if @driver.docs
        = link_to 'Descargar documentos', @driver.docs_url(:docs)
  .row
    .actions-form
      = f.submit 'Guardar', class: 'btn btn-primary'
     

app/views/drivers/_filter.html.haml
.row
  .gray-frame
    = search_form_for @q, url: drivers_path, class: 'filters' do |f|
      .row
        .col-md-2.col-sm-12.col
          = f.label :nombre
          = f.search_field :nombre_cont, class: 'form-control'
        .col-md-2.col-sm-12.col
          = f.label :cedula
          = f.search_field :cedula_start, class: 'form-control'
        .col-md-2.col-sm-12.col-sm-12.col
          = f.label 'Activo?'
          = f.select :activo_false,  options_for_select([ ['Si', 0], ['No', 1] ]), { include_hidden: false }, class: 'form-control'
        .col-md-1.col-sm-12.col.actions
          = f.submit 'Buscar', class: 'btn btn-primary'
    

app/views/drivers/_form.html.haml
= bootstrap_form_tag(url: :drivers) do |f|
  .row
    .col-md-3
      = f.text_field :nombre, {required: 'required'}
    .col-md-3
      = f.text_field :cedula, {required: 'required'}
    .col-md-3
      = f.email_field :email
    .col-md-3
      = f.phone_field :telefono
  .row    
    .col-md-6
      = f.text_area :direccion
    .col-md-3
      = f.form_group :activo, label: { text: '¿Activar el taxista?' } do
        = f.check_box :activo, label: 'Activar'
  .row
    .col-md-3
      = f.file_field :photo, as: :file, accept: DriverPhotoUploader::ALLOWED_TYPES.join(',')
    .col-md-3
      = f.file_field :docs, as: :file, accept: DocsUploader::ALLOWED_TYPES.join(',')
  .row
    .actions-form
      = f.submit 'Crear', class: 'btn btn-primary'
     

app/views/drivers/edit.html.haml
.int-content
	.form-title Editando taxista
	= render partial: 'edit_form'

app/views/drivers/index.html.haml
.int-content
  .form-title
    Lista de Conductores
    .model-action
      %span.badge.badge-secondary.secondary
        = link_to 'Crear conductor', new_driver_path
  = render partial: 'filter'
  .horizontal-divider
  .drivers
    - @drivers.each do |driver|
      .row.driver{ class: 'clickable-row', 'data-href': edit_driver_path(driver)}
        .col-lg-12
          .driver-info
            .image-driver
              - if driver.photo_url(:photo)
                .round
                  = image_tag driver.photo_url(:photo)
              - else
                .round
                  = gravatar_image_tag(driver.email)
            .driver-data
              .driver-name
                %b
                  = driver.nombre
              .driver-placa
                - if driver.taxis.count > 0
                  - driver.taxis.each do |taxi|
                    %span.placa-taxista.badge
                      = taxi.placa
                - else
                  %span.placa-taxista.badge
                    = 'Sin taxi asignado'
          .actions
            - if driver.activo?
              %span.green-label Activo
            - else
              %span.red-label Inactivo

app/views/drivers/new.html.haml
.int-content
	.form-title Nuevo taxista
	= render partial: 'form'