config/routes.rb
Rails.application.routes.draw do
  get 'questions/index'

  get 'recharge_homes/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/auth', to: 'authentication#autenthicate_user'
  get '/logout', to: 'authentication#logout_user'
  get '/audited/:model/:id', to: 'audited#index'


  resources :inboxes
  resources :subscribers

  namespace :api do
    namespace :v1 do
      post '/logout', to: 'users#logout'
      get '/me', to: 'users#me'
      get '/password_update/:id', to:'users#show'
      put '/password_update/:id', to:'users#password_update'
      resources :users
      resources :drivers
      resources :packages
      resources :recharges
      resources :questions
      resources :recharge_homes
      resources :taxis
      resources :assign_taxis
      resources :services
      resources :charts
    end
  end

  resources :taxis 
  resources :drivers 
  resources :packages
  resources :recharge_homes
  resources :questions

  get 'logout_driver/:taxi_id/:user_id', to: 'taxis#logout_driver', as: :logout_driver_and_taxi
  get 'add_driver_to_taxi/:taxi_id/:user_id', to: 'taxis#add_driver', as: :add_driver_to_taxi
  get 'remove_driver_from_taxi/:taxi_id/:user_id', to: 'taxis#remove_driver', as: :remove_driver_to_taxi


  get 'users/sign_in', to: 'users#sign_in', as: :sign_in
  get 'users/logout_user', to: 'users#logout_user', as: :logout_user
  post 'users/sign_in', to: 'users#new_session', as: :new_session

  root :controller => 'home', :action => 'home'
  mount Shrine.presign_endpoint(:cache) => '/presign'
end

app/views/layouts/_breadcrumbs.html.haml
%ol.breadcrumb
  - breadcrumb_trail do |crumb|
    - if "/#{controller_name}/#{action_name}" == crumb.path 
      %li.breadcrumb-item.opaque
        = crumb.name
    - else
      %li.breadcrumb-item{class: 'active'}
        = link_to crumb.name, crumb.url, (crumb.current? ? {'aria-current' => 'page'} : {})
      

app/views/layouts/_facebook_messenger_chatbot.html.haml
/ Load Facebook SDK for JavaScript
#fb-root
:javascript
  window.fbAsyncInit = function() {
      FB.init({
        xfbml            : true,
        version          : 'v3.2'
      });
    };
  
    (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/es_LA/sdk/xfbml.customerchat.js';
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
/ Your customer chat code
.fb-customerchat{:attribution => "setup_tool", :logged_in_greeting => "¡Hola! ¿Como te podemos ayudar?", :logged_out_greeting => "¡Hola! ¿Como te podemos ayudar?", :page_id => "1040222419443578", :theme_color => "#0084ff"}

app/views/layouts/_sidebar.html.haml
.nav-side-menu
  .brand.top-brand
    .content-top
      = image_tag('logo.png', class: 'logo-admin')
      %span.badge.badge-secondary Taxitura
  %i.fa.fa-bars.fa-2x.toggle-btn{"data-target" => "#menu-content", "data-toggle" => "collapse"}
  .menu-list
    %ul#menu-content.menu-content.collapse.out
      - if current_user.has_role? :admin
        = render partial: 'menu/admin'
      / %li
      /   %a
      /     %i.fa.fa-dashboard.fa-lg
      /     Dashboard
      / %li.collapsed.active{"data-target" => "#products", "data-toggle" => "collapse"}
      /   %a
      /     %i.fa.fa-gift.fa-lg
      /     UI Elements
      /     %span.arrow
      / %ul#products.sub-menu.collapse
      /   %li.active
      /     %a CSS3 Animation
      /   %li
      /     %a General
      /   %li
      /     %a Buttons
      /   %li
      /     %a Tabs  Accordions
      /   %li
      /     %a Typography
      /   %li
      /     %a FontAwesome
      /   %li
      /     %a Slider
      /   %li
      /     %a Panels
      /   %li
      /     %a Widgets
      /   %li
      /     %a Bootstrap Model
      / %li.collapsed{"data-target" => "#service", "data-toggle" => "collapse"}
      /   %a
      /     %i.fa.fa-globe.fa-lg
      /     Services
      /     %span.arrow
      / %ul#service.sub-menu.collapse
      /   %li New Service 1
      /   %li New Service 2
      /   %li New Service 3
      / %li.collapsed{"data-target" => "#new", "data-toggle" => "collapse"}
      /   %a
      /     %i.fa.fa-car.fa-lg
      /     New
      /     %span.arrow
      / %ul#new.sub-menu.collapse
      /   %li New New 1
      /   %li New New 2
      /   %li New New 3
      / %li
      /   %a
      /     %i.fa.fa-user.fa-lg
      /     Profile
      / %li
      /   %a
      /     %i.fa.fa-users.fa-lg
      /     Users

app/views/layouts/_topbar.html.haml
.btn-group
  %button.btn.btn-default.dropdown-toggle.especial_button{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
    = current_user.nombre
    %span.caret
  %ul.dropdown-menu
    %li
      = link_to 'Cerrar sesion', logout_user_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Taxitura
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyCpOuqlNsEV9WQGN4EhGFHiR9gm80IFQGM&callback=initMap"}
      :cdata
    %link{:href => image_path('logo.png'), :rel => "shortcut icon", :type => "image/png"}/
  %body
    = render 'toastr_rails/flash'
    - if is_home?
      = yield
    - else
      - if current_user
        = render partial: 'layouts/sidebar'
        .topbar.brand
          = render partial: 'layouts/topbar'
        .main-content
          = render partial: 'layouts/breadcrumbs'
          = yield
      - else
        .container
          = yield
    = render partial: 'layouts/facebook_messenger_chatbot'